### ISSUE TITLE
anderen SSH-Port als 22 ?

### ISSUE THREAD

**Issue by wegomyway** [toafez/HowTo_Windows.SSH.Powershell#1]
Beim Abarbeiten des type $env:USERPROFILE\.ssh\id_rsa.pub | ssh [BENUTZERNAME]@[IP-ADRESSE] "cat >> .ssh/authorized_keys" wird SSH-Port 22 "automatisch" erwartet. Nutze aber einen 5stelligen anderen Port.

**Comment by toafez** [comment]
Hallo und vielen Dank für deinen Hinweis. Ich habe den Text entsprechend ergänzt.  Du kannst meine Änderungen in [diesem Commit](https://github.com/toafez/HowTo_Windows.SSH.Powershell/commit/e6f39ab3e027290f6321964f51ffc92f2019b58e)überprüfen, wenn du magst.
